# Generated by Django 5.2 on 2025-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_remove_stall_created_at_stall_price_stall_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_end_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='event_start_date',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='stall',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20),
        ),
    ]
