# Generated by Django 5.2 on 2025-04-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_remove_booking_event_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stall',
        ),
        migrations.AddField(
            model_name='booking',
            name='stalls',
            field=models.ManyToManyField(related_name='bookings', to='halls.stall'),
        ),
    ]
