# Generated by Django 5.2 on 2025-04-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_remove_booking_stall_booking_stalls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='stall',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
