# Generated by Django 5.2 on 2025-04-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0005_alter_booking_status_alter_stall_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional custom price for the combo. If not set, will use sum of stall prices.', max_digits=10, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combos', to='halls.hall')),
                ('stalls', models.ManyToManyField(related_name='combos', to='halls.stall')),
            ],
        ),
    ]
