# Generated by Django 5.2 on 2025-04-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_combostall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='booked', max_length=20),
        ),
        migrations.AlterField(
            model_name='stall',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
    ]
