# Generated by Django 5.2 on 2025-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0007_alter_booking_status_alter_stall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combostall',
            name='price',
            field=models.DecimalField(decimal_places=2, default=130000.0, help_text='Default price for combo stalls is ₹1,30,000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stall',
            name='price',
            field=models.DecimalField(decimal_places=2, default=55000.0, max_digits=10),
        ),
    ]
