# Generated by Django 5.2 on 2025-04-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0008_alter_combostall_price_alter_stall_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
