# Generated by Django 5.2 on 2025-04-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0009_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_admin_booking',
            field=models.BooleanField(default=False),
        ),
    ]
