# Generated by Django 5.2 on 2025-05-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0010_booking_is_admin_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='stall_type',
            field=models.CharField(choices=[('eatery', 'Eatery'), ('non-eatery', 'Non-Eatery')], default='eatery', max_length=20),
        ),
    ]
