# Generated by Django 5.2 on 2025-05-06 11:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0011_stall_stall_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('cancellation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stall_ids', models.JSONField(default=list, help_text='Stores stall IDs if cancellation happens before booking is created')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='halls.booking')),
            ],
        ),
    ]
